export const phonedata = [{
    id:1,
    image:"https://cdn.lotuselectronics.com/webpimages/612961IM.webp",
    name:"Oppo Android Smartphone Reno 10 Pro",
    desc:"Oppo Android Smartphone Reno10 Pro + 5G | 6.74 inch, Full HD+, Rear Camera 50MP + 64 MP Telephoto + 8 MP, Front Camera 32",
    price:"54,999",
    brand:"Oppo",
    ram:"12GB RAM",
    storage:"256GB ROM",
    offer:"60,000",
    color:"silver gray",
    image2:"https://cdn.lotuselectronics.com/webpimages/612962IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/612963IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/612964IM.webp"
},{
    id:2,
    image:"https://cdn.lotuselectronics.com/webpimages/611841IM.webp",
    name:"Samsung Galaxy A34 NODE 5G ",
    desc:"Samsung Android Smartphone A34 5G (8GB RAM, 256GB Storage/ROM) Awesome Violet | 6.6 inch Super AMOLED, Rear Camera 48 MP+8MP+5, Front Camera 13 MP",
    price:"31,000",
    brand:"Samsung",
    ram:"8GB RAM",
    offer:"60,000",
    color:"Awesome violet",
    storage:"256GB ROM",
    image2:"https://cdn.lotuselectronics.com/webpimages/611842IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/611843IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/611844IM.webp"

},{
    id:3,
    offer:"1,49,000",
    image:"https://cdn.lotuselectronics.com/webpimages/591641IM.webp",
    name:"Samsung Android Smartphone S23 Ultra 5G ",
    desc:"Samsung Android Smartphone S23 Ultra 5G | S918BC Phantom Black | 6.8 inch Dynamic AMOLED 2X, Rear Camera 200 MP+10MP+10+12 MP, Front Camera 12 MP",
    price:"1,24,999",
    brand:"Samsung",
    color:"Phantom Black",
    ram:"12GB RAM",
    storage:"256GB ROM",
    image2:"https://cdn.lotuselectronics.com/webpimages/591642IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/591643IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/591644IM.webp"
},{
    id:4,
    offer:"19,999",
    image:"https://cdn.lotuselectronics.com/webpimages/513871IM.webp",
    name:"OnePlus Android Smartphone Nord CE 2 Lite 5G",
    desc:"OnePlus Android Smartphone Nord CE 2 Lite 5G  CPH2381 IN Black Dusk | 6.59 inch Full HD+, Rear Camera 64 MP + 2 MP + 2 MP, Front Camera 16 MP, Android",
    price:"17,999",
    brand:"oneplus",
    ram:"6GB RAM",
    color:"Black dusk",
    storage:"128GB ROM",
    image2:"https://cdn.lotuselectronics.com/webpimages/513872IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/513873IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/513874IM.webp"
},{
    id:5,
    offer:"60,000",
    image:"https://cdn.lotuselectronics.com/webpimages/509991IM.webp",
    name:"Apple iPhone Mobile 13",
    desc:"Apple iPhone Mobile 13 (128GB ROM) MNGK3HN/A Alpine Green",
    price:"59,999",
    brand:"ios",
    ram:"",
    color:"Alphine green",
    storage:"128GB ROM",
    image2:"https://cdn.lotuselectronics.com/webpimages/509992IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/509993IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/509994IM.webp"
},{
    id:6,
    offer:"89,000",

    image:"https://cdn.lotuselectronics.com/webpimages/538261IM.webp",
    name:"Apple iPhone Mobile 14",
    desc:"Apple iPhone Mobile 14 (256GB ROM) MPWA3HN/A Purple",
    price:"80,000",
    brand:"ios",
    ram:"",
    color:"Purple",
    storage:"256GB ROM",
    image2:"https://cdn.lotuselectronics.com/webpimages/538262IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/538263IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/538264IM.webp"
},{
    id:7,
    offer:"75,000",

    image:"https://cdn.lotuselectronics.com/webpimages/494991IM.webp",
    name:"Apple iPhone Mobile 13",
    desc:"Apple iPhone Mobile 13 (128GB ROM) MNGK3HN/A Alpine Gold",
    price:"69,900",
    brand:"ios",
    ram:"",
    color:"Gold",
    storage:"256GB",
    image2:"https://cdn.lotuselectronics.com/webpimages/494992IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/494993IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/494995IM.webp"
},{
    id:8,
    image:"https://cdn.lotuselectronics.com/webpimages/608831IM.webp",
    name:"Realme Android Smartphone 11 Pro 5G",
    desc:"Realme Android Smartphone 11 Pro + 5G | 11 Pro+ RMX3741 Oasis Green | 17.02 cm Curve Vision Display+, Rear Camera 200 MP + Front Camera 32 MP",
    offer:"32,990",
    price:"24,299",
    brand:"realme",
    ram:"8GB RAM",
    color:"Oasis Green",
    storage:"256GB ROM",
    image2:"https://cdn.lotuselectronics.com/webpimages/608832IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/608833IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/608835IM.webp"
},{
    id:9,
    image:"https://cdn.lotuselectronics.com/webpimages/513881IM.webp",
    name:"OnePlus Android Smartphone Nord CE 2 Lite 5G",
    desc:"OnePlus Android Smartphone Nord CE 2 Lite 5G  CPH2381 IN Blue Tide | 6.59 inch Full HD+, Rear Camera 64 MP + 2 MP + 2 MP, Front Camera 16 MP",
    price:"17,999",
    brand:"oneplus",
    ram:"6GB RAM",
    offer:"19,999",
color:"Blue Tide",
    storage:"128GB ROM",
    image2:"https://cdn.lotuselectronics.com/webpimages/513882IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/513883IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/513884IM.webp"
},{
    id:10,
    image:"https://cdn.lotuselectronics.com/webpimages/516601IM.webp",
    name:"Vivo Android Smartphone Y75 4G",
    desc:"Vivo Android Smartphone Y75 4G  V2117 Dancing Waves | 6.44 inch Full HD+, Rear Camera 50 MP + 8 MP + 2 MP, Front Camera 44 MP",
    price:"19,999",
    brand:"vivo",
    ram:"8GB RAM",
    offer:"22,000",
color:"Dancing waves",
    storage:"128GB ROM",
    image2:"https://cdn.lotuselectronics.com/webpimages/516602IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/516603IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/516604IM.webp"
},{
    id:11,
    image:"https://cdn.lotuselectronics.com/webpimages/610421IM.webp",
    name:"Realme Android Smartphone C55",
    desc:"Realme Android Smartphone C55 | RMX3710 Rainforest | Rear Camera 64 MP +2 MP , Front Camera 8 MP",
    price:"12,999",
    brand:"realme",
    ram:"6GB RAM",
    offer:"15,788",
    color:"Rain forest",
    storage:"64GB ROM",
    image2:"https://cdn.lotuselectronics.com/webpimages/610422IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/610423IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/610424IM.webp"
},{
    id:12,
    image:"https://cdn.lotuselectronics.com/webpimages/558521IM.webp",
    name:"Oppo Android Smartphone A17",
    desc:"Oppo Android Smartphone A17  CPH2477 Sunlight Orange | Octa Core, 2.3GHz Camera : 50MP + 0.3MP + 0.3MP Triple Rear & 5MP Front Camera B",
    price:"11,999",
    brand:"oppo",
    offer:"15,500",
    ram:"4GB RAM",
    color:"Sunlight orange",
    storage:"64GB ROM",
    image2:"https://cdn.lotuselectronics.com/webpimages/558522IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/558523IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/558525IM.webp"
},{
    id:13,
    image:"https://cdn.lotuselectronics.com/webpimages/477791IM.webp",
    name:"HP Windows Laptop i5, 11th, 8GB, 1TB HDD",
    desc:"HP Windows Laptop i5, 11th, 8GB, 1TB HDD, 2GB, 15.6FHD, W10, MSO Addl 240GB SSD 15S-DU3060TX Jet Black | 2GB - MX350 GFX",
    price:"58,999",
    brand:"hp",
    offer:"69,000",
    Ram:"8GB",
    ssd:"1TB",
    ram:"8GB RAM",
    storage:"1TB HDD",
    color:"Jet Black",
    processor:"i5",
    image2:"https://cdn.lotuselectronics.com/webpimages/477792IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/477793IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/477794IM.webp"
},{
    id:14,
    name:"Apple MacBook Laptop M1",
    image:"https://cdn.lotuselectronics.com/ItemImages/472691IM.jpeg",
    image2:"https://cdn.lotuselectronics.com/ItemImages/472692IM.jpeg",
    image3:"https://cdn.lotuselectronics.com/ItemImages/472693IM.jpeg",
    image4:"https://cdn.lotuselectronics.com/ItemImages/472695IM.jpeg",
    desc:"Apple MacBook Laptop M1, 8GB, 256GB, 13.3 Air MGN63HN/A Space Grey | M1 Chip, 8GB RAM, 256GB SSD, 13.3 inch",
    brand:"apples",
    price:"89,900",
    offer:"99,900",
    Ram:"8GB",
    ssd:"256GB",
    processor:"",
    ram:"8GB RAM",
    storage:"256 SSD",
    color:"Grey",
},{
    id:15,
    name:"Apple MacBook Laptop M2",
    image:"https://cdn.lotuselectronics.com/webpimages/524401IM.webp",
    image2:"https://cdn.lotuselectronics.com/webpimages/524402IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/524403IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/524404IM.webp",
    desc:"Apple MacBook Laptop M1, 8GB, 256GB, 13.3 Air MGN63HN/A Space Grey | M1 Chip, 8GB RAM, 256GB SSD, 13.3 inch",
    brand:"apples",
    price:"1,14,900",
    offer:"1,20,000",
    Ram:"8GB",
    ssd:"256GB",
    processor:"",
    ram:"8GB RAM",
    storage:"256 SSD",
    color:"Black",
},{
    id:16,
    name:"HP Convertible Laptop i5",
    image:"https://cdn.lotuselectronics.com/webpimages/566781IM.webp",
    image2:"https://cdn.lotuselectronics.com/webpimages/566782IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/566783IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/566784IM.webp",
    desc:"12th, 16GB, 512GB SSD, 14 FHD, W11, MSO 21 Pavilion x360 14-EK0072TU Rose Gold | Intel UHD Graphics, IPS Micro-Edge FHD Laptop, B&O, Alexa Built-in, Backlit KB",
    brand:"hp",
    price:"79,299",
    offer:"85,000",
    Ram:"16GB",
    ssd:"512GB",
    processor:"i5",
    ram:"8GB RAM",
    storage:"512 SSD",
    color:"Rose Gold",
},{
    id:17,
    name:"Lenovo Thin & Light Laptop Ryzen 7 5700U",
    image:"https://cdn.lotuselectronics.com/webpimages/594401IM.webp",
    image2:"https://cdn.lotuselectronics.com/webpimages/594402IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/594404IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/594405IM.webp",
    desc:"Fingerprint Reader, Anti Glare Screen, Backlit Keyboard, Built-in Microphone",
    brand:"lenovo",
    price:"68,399",
    offer:"93,000",
    Ram:"16GB",
    ssd:"512GB",
    processor:"ryzen",
    ram:"16GB RAM",
    storage:"512 SSD",
    color:"Black",
},{
    id:18,
    name:"Lenovo Thin & Light Laptop Ryzen 3",
    image:"https://cdn.lotuselectronics.com/webpimages/613571IM.webp",
    image2:"https://cdn.lotuselectronics.com/webpimages/613572IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/613573IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/613575IM.webp",
    desc:"Lenovo Thin & Light Laptop Ryzen 315.6 FHD (1920x1080) TN 250nits Anti-glare, Camera privacy shutter",
    brand:"lenovo",
    price:"38,399",
    offer:"41,399",
    Ram:"8GB",
    ssd:"512GB",
    processor:"ryzen",
    ram:"8GB RAM",
    storage:"512 SSD",
    color:"Grey",
},{
    id:19,
    name:"Lenovo Gaming Laptop i5-11300H",
    image:"https://cdn.lotuselectronics.com/webpimages/569451IM.webp",
    image2:"https://cdn.lotuselectronics.com/webpimages/569452IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/569453IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/569454IM.webp",
    desc:"15.6 FHD, W11, MSO IdeaPad Gaming 3 82K1019BIN Shadow Black | NVIDIA GeForce RTX 3050 4GB GDDR6, Backlit KB",
    brand:"lenovo",
    price:"79,299",
    offer:"85,999",
    Ram:"16GB",
    ssd:"512GB",
    processor:"i5",
    ram:"16GB RAM",
    storage:"512 SSD",
    color:"Black",
},{
    id:20,
    name:"HP Gaming Laptop i5-13420H",
    image:"https://cdn.lotuselectronics.com/webpimages/618891IM.webp",
    image2:"https://cdn.lotuselectronics.com/webpimages/618892IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/618893IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/618894IM.webp",
    desc:"6GB,512GB SSD, 16 FHD,6GB RTX 4050 Win 11,MS Office 2021,RGB Backlit Omen 16-WD0990TX Shadow Black | 250 Nits Brightness, Diagonal, FHD, Micro-edge",
    brand:"hp",
    price:"1,09,000",
    offer:"1,23,000",
    Ram:"16GB",
    ssd:"512GB",
    processor:"i5",
    ram:"16GB RAM",
    storage:"512 SSD",
    color:"Black",
},{
    id:21,
    name:"Dell Convertible Laptop i5-1335U",
    image:"https://cdn.lotuselectronics.com/webpimages/603621IM.webp",
    image2:"https://cdn.lotuselectronics.com/webpimages/603622IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/603623IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/603625IM.webp",
    desc:" Office H&S 2021,Backlit, FingerPrint Inspiron 7430 IC7430PXXWC001ORS1 / IC7430MH5K0M01ORS1 Platinum Silver",
    brand:"dell",
    price:"79,399",
    offer:"82,000",
    Ram:"8GB",
    ssd:"512GB",
    processor:"i5",
    ram:"8GB RAM",
    storage:"512 SSD",
    color:"Silver",
},{
    id:22,
    name:"Asus Gaming Laptop i5-12500H,",
    image:"https://cdn.lotuselectronics.com/webpimages/622671IM.webp",
    image2:"https://cdn.lotuselectronics.com/webpimages/622672IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/622673IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/622674IM.webp",
    desc:"8GB,512 SS,4GB RTX 3050,15.6 FHD, RGB Backlit KB,Win 11 TUF F15 FX507ZC4-HN115WS Mecha Gray",
    brand:"asus",
    price:"86,699",
    offer:"90,299",
    Ram:"8GB",
    ssd:"512GB",
    processor:"i5",
    ram:"8GB RAM",
    storage:"512 SSD",
    color:"Gray",
},{
    id:23,
    name:"Dell Thin & Light Laptop R5-5625U",
    image:"https://cdn.lotuselectronics.com/webpimages/576421IM.webp",
    image2:"https://cdn.lotuselectronics.com/webpimages/576422IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/576423IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/576424IM.webp",
    desc:"Dell Thin & Light Laptop R5-5625U 8GB, 512GB SSD,15.6 FHD, W11, MSO New Inspiron 15 D560863WIN9B carbon black | Integrated Graphics",
    brand:"dell",
    price:"49,199",
    offer:"55,300",
    Ram:"8GB",
    ssd:"512GB",
    processor:"ryzen",
    ram:"8GB RAM",
    storage:"512 SSD",
    color:"Carbon Black",
},{
    id:24,
    name:"Samsung HD LED TV 80 cm (32 inches) UA32T4350 Black",
    image:"https://cdn.lotuselectronics.com/webpimages/454381IM.webp",
    image2:"https://cdn.lotuselectronics.com/webpimages/454382IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/454383IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/454384IM.webp",
    desc:" Ultra Pix & HDR, Personal Computer, Content Guide",
    brand:"samsung",
    price:"18,099",
    offer:"20,779",
    display:"hd-led",
    screen:"32",
    color:"Black",
    ram:"HD LED",
    storage:"32 INCH"

},{
    id:25,
    name:"Sansui HD LED TV 80 cm (32 inches) ",
    image:"https://cdn.lotuselectronics.com/webpimages/502301IM.webp",
    image2:"https://cdn.lotuselectronics.com/webpimages/502302IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/502304IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/502305IM.webp",
    desc:" JSY32SKHD Black | Smart TV, Prime Series",
    brand:"sansui",
    price:"10,799",
    offer:"12,299",
    display:"hd-led",
    screen:"32",
    ram:"HD LED",
    storage:"32 INCH",
    color:"Black"
},{
    id:26,
    name:"Amstrad HD LED TV 80 cm (32 inches) ",
    image:"https://cdn.lotuselectronics.com/webpimages/598671IM.webp",
    image2:"https://cdn.lotuselectronics.com/webpimages/598672IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/598673IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/598674IM.webp",
    desc:"Amstrad HD LED TV 80 cm (32 inches) AM32FTA6A Black",
    brand:"amstrad",
    price:"9,999",
    offer:"19,990",
    display:"hd-led",
    screen:"32",
    color:"Black",
    ram:"HD LED",
    storage:"32 INCH"
},{
    id:27,
    name:"Samsung 4K Ultra HD TV 138 cm",
    image:"https://cdn.lotuselectronics.com/webpimages/485601IM.webp",
    image2:"https://cdn.lotuselectronics.com/webpimages/485602IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/485603IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/485604IM.webp",
    desc:"(55 inches) UA55AU7700 Black | 4K Resolution, Crystal Display, HDR, Crystal Processor,3 Side Bezel-less Design",
    brand:"samsung",
    price:"54,199",
    offer:"79,400",
    display:"4k",
    screen:"55",
    color:"Black",
    ram:"4K ULTRA HD",
    storage:"55 INCH"
},{
    id:28,
    name:"LG 4K Ultra HD TV 139 cm (55 inches)",
    image:"https://cdn.lotuselectronics.com/webpimages/518851IM.webp",
    image2:"https://cdn.lotuselectronics.com/webpimages/518852IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/518853IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/518854IM.webp",
    desc:"LG 4K Ultra HD TV 139 cm (55 inches) 55UQ7550 Black",
    brand:"lg",
    price:"48,199",
    offer:"71,990",
    display:"4k",
    screen:"55",
    color:"Black",
    ram:"4K ULTRA HD",
    storage:"55 INCH"
},{
    id:29,
    name:"Haier 4K Ultra HD TV 139 cm (55 inches)",
    image:"https://cdn.lotuselectronics.com/webpimages/613631IM.webp",
    image2:"https://cdn.lotuselectronics.com/webpimages/613632IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/613633IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/613634IM.webp",
    desc:" Android LE55K7500HQGA Black | AI Smart Voice by Google Assistant,Google Certified - Android 11",
    brand:"haier",
    price:"41,399",
    offer:"80,990",
    display:"4k",
    screen:"55",
    color:"Black",
    ram:"4K ULTRA HD",
    storage:"55 INCH"
},{
    id:30,
    name:"OnePlus 4K Ultra HD TV 138 cm (55 inches)",
    image:"https://cdn.lotuselectronics.com/webpimages/577921IM.webp",
    image2:"https://cdn.lotuselectronics.com/webpimages/577922IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/577923IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/577924IM.webp",
    desc:" 55Y1S Pro Black | Android TV | OnePlus Connect Ecosystem| Google Assistant | Chromecast, Miracast ",
    brand:"oneplus",
    price:"39,999",
    offer:"49,999",
    display:"4k",
    screen:"55",
    color:"Black",
    ram:"4K ULTRA HD",
    storage:"55 INCH"
},{
    id:31,
    name:"LG 8K Ultra HD TV 189 cm (75 inches)",
    image:"https://cdn.lotuselectronics.com/webpimages/552341IM.webp",
    image2:"https://cdn.lotuselectronics.com/webpimages/552342IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/552343IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/552344IM.webp",
    desc:"LG 8K Ultra HD TV 189 cm (75 inches) 75UR8040 Black | α5 AI Processor 4K Gen6 with AI Brightness & 4K Upscaling ",
    brand:"lg",
    price:"1,23,699",
    offer:"2,24,990",
    display:"8k",
    screen:"75",
    color:"Black",
    ram:"8K ULTRA HD",
    storage:"75 INCH"
},{
    id:32,
    name:"OnePlus Full HD LED TV 102 cm (40 inches)",
    image:"https://cdn.lotuselectronics.com/webpimages/498661IM.webp",
    image2:"https://cdn.lotuselectronics.com/webpimages/498662IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/498663IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/498664IM.webp",
    desc:"Android 40Y1 Black",
    brand:"oneplus",
    price:"21,999",
    offer:"27,999",
    display:"hd-led",
    screen:"32",
    color:"Black",
    ram:"HD LED",
    storage:"32 INCH"
},{
    id:33,
    name:"Amstrad 4K Ultra HD TV 138 cm (55 inches)",
    image:"https://cdn.lotuselectronics.com/webpimages/589301IM.webp",
    image2:"https://cdn.lotuselectronics.com/webpimages/589302IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/589303IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/589304IM.webp",
    desc:" AM55UG11NXT Black |  SMART TV FEATURES | CHROMECAST BUILT-IN ",
    brand:"amstrad",
    price:"38,299",
    offer:"45,999",
    display:"4k",
    screen:"55",
    color:"Black",
    ram:" 4K ULTRA HD",
    storage:"55 INCH"
},{
    id:34,
    name:"Samsung Double Door Refrigerator",
    image:"https://cdn.lotuselectronics.com/webpimages/503531IM.webp",
    image2:"https://cdn.lotuselectronics.com/webpimages/503532IM.webp",
    image3:"",
    image4:"",
    desc:" 336 Litres 3 Star Inverter RT37A4633S8 Elegant Inox | Convertible 5in1, Curd Maestro, Digital Inverter Technology, Twin Cooling Plus™",
    brand:"samsung",
    price:"38,399",
    offer:"56,990 ",
    door:"double",
    freezer:"top",
    star:"3",
    capacity:"300",
    ram:"Double door",
    storage:"336 Ltr",
    color:"Gray",

},{
    id:35,
    name:"Whirlpool Double Door Refrigerator ",
    image:"https://cdn.lotuselectronics.com/webpimages/621711IM.webp",
    image2:"https://cdn.lotuselectronics.com/webpimages/621712IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/621714IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/621715IM.webp",
    desc:"235 Litres 2 Star Inverter IF INV ELT 278LH Wine Palm (2S)-TL | 3 sensers ,15 days freshness ,ACTIVE DEO,Deep freezer technology",
    brand:"whirlpool",
    price:"26,499",
    offer:"33,850",
    door:"double",
    freezer:"top",
    ram:"Double door",
    storage:"235 Ltr",
    color:"Black",
    capacity:"200",
    star:"2"
},{
    id:36,
    name:"Godrej Double Door Refrigerator",
    image:"https://cdn.lotuselectronics.com/webpimages/605741IM.webp",
    image2:"https://cdn.lotuselectronics.com/webpimages/605742IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/605743IM.webp",
    image4:"",
    desc:"308 Litres 2 Star Inverter RT EONVIBE 346B HCIT ST RH Steel Rush | Patented Cool Shower Technology 4-1 Total convertible modes Adjustable Toughened",
    brand:"godrej",
    price:"37,399",
    offer:"48,090",
    door:"double",
    ram:"Double door",
    storage:"308 Ltr",
    color:"Silver lite",
    freezer:"top",
    capacity:"300",
    star:"2"
},{
    id:37,
    name:"LG Side By Side Refrigerator",
    image:"https://cdn.lotuselectronics.com/webpimages/604781IM.webp",
    image2:"https://cdn.lotuselectronics.com/webpimages/604782IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/604783IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/604784IM.webp",
    desc:"635 Litres Inverter GL-X257AMCX Matt Black | AI ThinQ Wi-Fi InstaView Door-in-Door UV Nano Dispenser Hygiene Fresh DoorCoolin ",
    brand:"lg",
    price:"1,62,199",
    offer:"2,27,099 ",
    door:"side by side",
    freezer:"top",
    capacity:"600",
    ram:"Side by side",
    storage:"635 Ltr",
    color:"Matt Black",
    star:"5"
},{
    id:38,
    name:"Haier Side By Side Refrigerator ",
    image:"https://cdn.lotuselectronics.com/webpimages/516431IM.webp",
    image2:"https://cdn.lotuselectronics.com/webpimages/516432IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/516433IM.webp",
    image4:"",
    desc:"628 Litres Inverter HRT-628PMGU1 Mirror Glass | Expert Inverter Technology, Convertible Zone, Noiseless Compressor",
    brand:"haier",
    price:"1,04,999",
    offer:"1,63,990",
    door:"side by side",
    freezer:"top",
    capacity:"600",
    ram:"Side by side",
    storage:"628 Ltr",
    color:"Silver",
    star:"5"
},{
    id:39,
    name:"Samsung Side By Side Refrigerator",
    image:"https://cdn.lotuselectronics.com/webpimages/595591IM.webp",
    image2:"https://cdn.lotuselectronics.com/webpimages/595592IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/595593IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/595594IM.webp",
    desc:"653 Litres 3 Star Inverter RS76CB811333HL Glam Deep Charcoal | WiFi Embedded,Power Freeze Function Twin Cooling Plus Wine Rack Manual Twist",
    brand:"samsung",
    price:"96,899",
    offer:"1,51,000",
    door:"side by side",
    freezer:"top",
    capacity:"600",
    ram:"Side by Side",
    storage:"653 Ltr",
    color:"Deep black",
    star:"5"
},{
    id:40,
    name:"Whirlpool Triple Door Refrigerator",
    image:"https://cdn.lotuselectronics.com/webpimages/319671IM.webp",
    image2:"https://cdn.lotuselectronics.com/webpimages/319672IM.webp",
    image3:"",
    image4:"",
    desc:"Whirlpool Triple Door Refrigerator 330 Litres FP 343D Protton Roy Alpha Steel (N) | 6TH SENSE® ActiveFresh Technology",
    brand:"whirlpool",
    price:"36,000",
    offer:"48,300 ",
    door:"triple",
    freezer:"top",
    capacity:"300",
    ram:"Triple Door",
    storage:"330 Ltr",
    color:"Alpha white",
    star:"4"
},{
    id:41,
    name:"Haier Bottom Freezer Refrigerator",
    image:"https://cdn.lotuselectronics.com/webpimages/430161IM.webp",
    image2:"https://cdn.lotuselectronics.com/webpimages/430162IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/430163IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/430164IM.webp",
    desc:"Haier Bottom Freezer Refrigerator 531 Litres Inverter HRB-550KG Black Glass | 100 % fridge, No Wall Partition, 0.95 Unit Consumption",
    brand:"haier",
    price:"79,999 ",
    offer:"1,39,990",
    door:"side by side",
    freezer:"bottom",
    ram:"Bottom freezer",
    storage:"531 Ltr",
    color:"Black glass",
    capacity:"600",
    star:"5"
},{
    id:42,
    name:"Hitachi Bottom Freezer Refrigerator ",
    image:"https://cdn.lotuselectronics.com/ItemImages/442401IM.jpg",
    image2:"https://cdn.lotuselectronics.com/ItemImages/442402IM.jpg",
    image3:"https://cdn.lotuselectronics.com/ItemImages/442403IM.jpg",
    image4:"",
    desc:"Hitachi Bottom Freezer Refrigerator 451 Litres Inverter R-WB490PND9 (GBK) Glass Black | Inverter Control, Dual Fan Cooling, Eco Thermo Sensor",
    brand:"hitachi",
    price:"75,999",
    offer:"1,05,700",
    door:"side by side",
    freezer:"bottom",
    ram:"Bottom freezer",
    storage:"451 Ltr",
    color:"Glass black",
    capacity:"300",
    star:"4"
},{
    id:43,
    name:"Godrej Double Door Refrigerator",
    image:"https://cdn.lotuselectronics.com/webpimages/605691IM.webp",
    image2:"https://cdn.lotuselectronics.com/webpimages/605692IM.webp",
    image3:"https://cdn.lotuselectronics.com/webpimages/605693IM.webp",
    image4:"https://cdn.lotuselectronics.com/webpimages/605694IM.webp",
    desc:"272 Litres 2 Star Inverter RT EONCRYSTAL 310B RI OB Onyx Black | Movable Ice Box Cool Balance Technology Upto 30 days farm freshness Adjustable",
    brand:"godrej",
    price:"32,899",
    offer:"41,590",
    door:"double",
    ram:"Double door",
    storage:"272 Ltr",
    color:"Onyx black",
    freezer:"top",
    capacity:"300",
    star:"3"
}]